version: '3.4'

services:
    dockercomposedemo:
        image: ${DOCKER_REGISTRY-}dockercomposedemo
        container_name: dockercomposedemo
        build:
          context: .
          dockerfile: DockerComposeDemo/Dockerfile


    sql-server-db :
        container_name: sql-server-db
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:                  
         - "1433:1433" 

        environment:
            MSSQL_SA_PASSWORD: "Pa$$_w0rd"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
            
        

    
#New_Pa$$_w0rd


